### ISSUE TITLE
JSONDecodeError at the second section 

### ISSUE THREAD

**Issue by MohamedNedal** [mbobra/magnetic-field-models#1] opened 2020-09-26 17:11 UTC
Hi! @mbobra 

I was trying your code but I got this error 

```
  File "C:\Users\DELL\anaconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None

JSONDecodeError: Expecting value
```

at the second section 
`c = drms.Client(email='mohamed.nedal.solar@gmail.com', verbose=True)
`
although my email is registered. How can I fix it please?

**Comment by mbobra** [comment] 2020-09-29 01:08
@MohamedNedal Hmmm, I don't know. Maybe the problem is with the version of drms. What is the output of `print(drms.__version__)`)? I am using version 0.5.7. In general, it makes sense to open issues with drms on the [drms repo](https://github.com/sunpy/drms).

**Comment by mbobra** [comment] 2020-10-19 18:02
@MohamedNedal I am going to close this issue. Also, please [register your e-mail here](http://jsoc.stanford.edu/ajax/register_email.html) to download JSOC data!

**Closed as completed by mbobra** 2020-10-19 18:02 UTC
